# Generated by Django 5.1.1 on 2024-10-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_detalle',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/detalle_pics'),
        ),
    ]
