# Generated by Django 5.1.1 on 2024-10-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_imagen_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
