# Generated by Django 5.1.1 on 2024-10-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_email_contacto_post_telefono_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
