# Generated by Django 5.1.1 on 2024-10-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_link1_post_link2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link2_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
